#!/bin/bash
echo "Attempting to install Node Version Manager (nvm)..."
echo "This script will run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash"
echo "----------------------------------------------------------------------"

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

echo "----------------------------------------------------------------------"
echo "NVM installation script has been executed."
echo ""
echo "IMPORTANT NEXT STEPS (You MUST do these manually):"
echo "1. CLOSE this terminal and OPEN a NEW terminal window."
echo "   Alternatively, you can try to source your shell's configuration file (e.g., run 'source ~/.zshrc' or 'source ~/.bashrc')."
echo ""
echo "2. In the NEW terminal, install the latest LTS (Long Term Support) version of Node.js:"
echo "   nvm install --lts"
echo ""
echo "3. Tell nvm to use this version:"
echo "   nvm use --lts"
echo ""
echo "4. Verify the installation by checking the versions:"
echo "   node -v"
echo "   npm -v"
echo ""
echo "5. Once Node.js and npm are confirmed to be working, navigate back to your project directory:"
echo "   cd /Users/startupomatic/Documents/work/mysticbanana"
echo ""
echo "6. Then, try running the dependency installation script again:"
echo "   sh/install_deps.sh"
echo "----------------------------------------------------------------------"
